package pojo;
// Generated Aug 2, 2017 11:22:50 AM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * AssetStatus generated by hbm2java
 */
public class AssetStatus  implements java.io.Serializable {


     private Integer id;
     private String asset;
     private Double amount;
     private Set assetLogs = new HashSet(0);

    public AssetStatus() {
    }

    public AssetStatus(String asset, Double amount, Set assetLogs) {
       this.asset = asset;
       this.amount = amount;
       this.assetLogs = assetLogs;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public String getAsset() {
        return this.asset;
    }
    
    public void setAsset(String asset) {
        this.asset = asset;
    }
    public Double getAmount() {
        return this.amount;
    }
    
    public void setAmount(Double amount) {
        this.amount = amount;
    }
    public Set getAssetLogs() {
        return this.assetLogs;
    }
    
    public void setAssetLogs(Set assetLogs) {
        this.assetLogs = assetLogs;
    }




}


