package pojo;
// Generated Aug 2, 2017 11:22:50 AM by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * AssetLog generated by hbm2java
 */
public class AssetLog  implements java.io.Serializable {


     private Long id;
     private AssetStatus assetStatus;
     private Date date;
     private String desceiption;

    public AssetLog() {
    }

	
    public AssetLog(AssetStatus assetStatus) {
        this.assetStatus = assetStatus;
    }
    public AssetLog(AssetStatus assetStatus, Date date, String desceiption) {
       this.assetStatus = assetStatus;
       this.date = date;
       this.desceiption = desceiption;
    }
   
    public Long getId() {
        return this.id;
    }
    
    public void setId(Long id) {
        this.id = id;
    }
    public AssetStatus getAssetStatus() {
        return this.assetStatus;
    }
    
    public void setAssetStatus(AssetStatus assetStatus) {
        this.assetStatus = assetStatus;
    }
    public Date getDate() {
        return this.date;
    }
    
    public void setDate(Date date) {
        this.date = date;
    }
    public String getDesceiption() {
        return this.desceiption;
    }
    
    public void setDesceiption(String desceiption) {
        this.desceiption = desceiption;
    }




}


