package pojo;
// Generated Aug 2, 2017 11:22:50 AM by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Attendence generated by hbm2java
 */
public class Attendence  implements java.io.Serializable {


     private Integer id;
     private Date date;
     private Set attenenceLogs = new HashSet(0);

    public Attendence() {
    }

    public Attendence(Date date, Set attenenceLogs) {
       this.date = date;
       this.attenenceLogs = attenenceLogs;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public Date getDate() {
        return this.date;
    }
    
    public void setDate(Date date) {
        this.date = date;
    }
    public Set getAttenenceLogs() {
        return this.attenenceLogs;
    }
    
    public void setAttenenceLogs(Set attenenceLogs) {
        this.attenenceLogs = attenenceLogs;
    }




}


