package pojo;
// Generated Aug 2, 2017 11:22:50 AM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Customer generated by hbm2java
 */
public class Customer  implements java.io.Serializable {


     private Integer id;
     private String fname;
     private String mname;
     private String lname;
     private String nic;
     private String gender;
     private String adressLine1;
     private String adressLine2;
     private String phone1;
     private String phone2;
     private Double credit;
     private String adressLine3;
     private Set invoices = new HashSet(0);
     private Set customerPays = new HashSet(0);
     private Set cusCredits = new HashSet(0);

    public Customer() {
    }

    public Customer(String fname, String mname, String lname, String nic, String gender, String adressLine1, String adressLine2, String phone1, String phone2, Double credit, String adressLine3, Set invoices, Set customerPays, Set cusCredits) {
       this.fname = fname;
       this.mname = mname;
       this.lname = lname;
       this.nic = nic;
       this.gender = gender;
       this.adressLine1 = adressLine1;
       this.adressLine2 = adressLine2;
       this.phone1 = phone1;
       this.phone2 = phone2;
       this.credit = credit;
       this.adressLine3 = adressLine3;
       this.invoices = invoices;
       this.customerPays = customerPays;
       this.cusCredits = cusCredits;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public String getFname() {
        return this.fname;
    }
    
    public void setFname(String fname) {
        this.fname = fname;
    }
    public String getMname() {
        return this.mname;
    }
    
    public void setMname(String mname) {
        this.mname = mname;
    }
    public String getLname() {
        return this.lname;
    }
    
    public void setLname(String lname) {
        this.lname = lname;
    }
    public String getNic() {
        return this.nic;
    }
    
    public void setNic(String nic) {
        this.nic = nic;
    }
    public String getGender() {
        return this.gender;
    }
    
    public void setGender(String gender) {
        this.gender = gender;
    }
    public String getAdressLine1() {
        return this.adressLine1;
    }
    
    public void setAdressLine1(String adressLine1) {
        this.adressLine1 = adressLine1;
    }
    public String getAdressLine2() {
        return this.adressLine2;
    }
    
    public void setAdressLine2(String adressLine2) {
        this.adressLine2 = adressLine2;
    }
    public String getPhone1() {
        return this.phone1;
    }
    
    public void setPhone1(String phone1) {
        this.phone1 = phone1;
    }
    public String getPhone2() {
        return this.phone2;
    }
    
    public void setPhone2(String phone2) {
        this.phone2 = phone2;
    }
    public Double getCredit() {
        return this.credit;
    }
    
    public void setCredit(Double credit) {
        this.credit = credit;
    }
    public String getAdressLine3() {
        return this.adressLine3;
    }
    
    public void setAdressLine3(String adressLine3) {
        this.adressLine3 = adressLine3;
    }
    public Set getInvoices() {
        return this.invoices;
    }
    
    public void setInvoices(Set invoices) {
        this.invoices = invoices;
    }
    public Set getCustomerPays() {
        return this.customerPays;
    }
    
    public void setCustomerPays(Set customerPays) {
        this.customerPays = customerPays;
    }
    public Set getCusCredits() {
        return this.cusCredits;
    }
    
    public void setCusCredits(Set cusCredits) {
        this.cusCredits = cusCredits;
    }




}


