package pojo;
// Generated Aug 2, 2017 11:22:50 AM by Hibernate Tools 4.3.1



/**
 * DealCheque generated by hbm2java
 */
public class DealCheque  implements java.io.Serializable {


     private Integer id;
     private BankDeals bankDeals;
     private Cheques cheques;

    public DealCheque() {
    }

    public DealCheque(BankDeals bankDeals, Cheques cheques) {
       this.bankDeals = bankDeals;
       this.cheques = cheques;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public BankDeals getBankDeals() {
        return this.bankDeals;
    }
    
    public void setBankDeals(BankDeals bankDeals) {
        this.bankDeals = bankDeals;
    }
    public Cheques getCheques() {
        return this.cheques;
    }
    
    public void setCheques(Cheques cheques) {
        this.cheques = cheques;
    }




}


