package pojo;
// Generated Aug 2, 2017 11:22:50 AM by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Delivery generated by hbm2java
 */
public class Delivery  implements java.io.Serializable {


     private Integer id;
     private Employee employeeByPartner2;
     private Employee employeeByPartner1;
     private Employee employeeByDriver;
     private RouteReg routeReg;
     private Vehicle vehicle;
     private Date date;
     private Set diliveryLoads = new HashSet(0);
     private Set deliveryItemLogs = new HashSet(0);

    public Delivery() {
    }

	
    public Delivery(Employee employeeByPartner2, Employee employeeByPartner1, Employee employeeByDriver, RouteReg routeReg, Vehicle vehicle) {
        this.employeeByPartner2 = employeeByPartner2;
        this.employeeByPartner1 = employeeByPartner1;
        this.employeeByDriver = employeeByDriver;
        this.routeReg = routeReg;
        this.vehicle = vehicle;
    }
    public Delivery(Employee employeeByPartner2, Employee employeeByPartner1, Employee employeeByDriver, RouteReg routeReg, Vehicle vehicle, Date date, Set diliveryLoads, Set deliveryItemLogs) {
       this.employeeByPartner2 = employeeByPartner2;
       this.employeeByPartner1 = employeeByPartner1;
       this.employeeByDriver = employeeByDriver;
       this.routeReg = routeReg;
       this.vehicle = vehicle;
       this.date = date;
       this.diliveryLoads = diliveryLoads;
       this.deliveryItemLogs = deliveryItemLogs;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public Employee getEmployeeByPartner2() {
        return this.employeeByPartner2;
    }
    
    public void setEmployeeByPartner2(Employee employeeByPartner2) {
        this.employeeByPartner2 = employeeByPartner2;
    }
    public Employee getEmployeeByPartner1() {
        return this.employeeByPartner1;
    }
    
    public void setEmployeeByPartner1(Employee employeeByPartner1) {
        this.employeeByPartner1 = employeeByPartner1;
    }
    public Employee getEmployeeByDriver() {
        return this.employeeByDriver;
    }
    
    public void setEmployeeByDriver(Employee employeeByDriver) {
        this.employeeByDriver = employeeByDriver;
    }
    public RouteReg getRouteReg() {
        return this.routeReg;
    }
    
    public void setRouteReg(RouteReg routeReg) {
        this.routeReg = routeReg;
    }
    public Vehicle getVehicle() {
        return this.vehicle;
    }
    
    public void setVehicle(Vehicle vehicle) {
        this.vehicle = vehicle;
    }
    public Date getDate() {
        return this.date;
    }
    
    public void setDate(Date date) {
        this.date = date;
    }
    public Set getDiliveryLoads() {
        return this.diliveryLoads;
    }
    
    public void setDiliveryLoads(Set diliveryLoads) {
        this.diliveryLoads = diliveryLoads;
    }
    public Set getDeliveryItemLogs() {
        return this.deliveryItemLogs;
    }
    
    public void setDeliveryItemLogs(Set deliveryItemLogs) {
        this.deliveryItemLogs = deliveryItemLogs;
    }




}


