package pojo;
// Generated Aug 2, 2017 11:22:50 AM by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * EmpCredit generated by hbm2java
 */
public class EmpCredit  implements java.io.Serializable {


     private Integer id;
     private Employee employee;
     private MoneyBook moneyBook;
     private Date date;
     private Double credit;
     private String sms;

    public EmpCredit() {
    }

	
    public EmpCredit(Employee employee, MoneyBook moneyBook) {
        this.employee = employee;
        this.moneyBook = moneyBook;
    }
    public EmpCredit(Employee employee, MoneyBook moneyBook, Date date, Double credit, String sms) {
       this.employee = employee;
       this.moneyBook = moneyBook;
       this.date = date;
       this.credit = credit;
       this.sms = sms;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public Employee getEmployee() {
        return this.employee;
    }
    
    public void setEmployee(Employee employee) {
        this.employee = employee;
    }
    public MoneyBook getMoneyBook() {
        return this.moneyBook;
    }
    
    public void setMoneyBook(MoneyBook moneyBook) {
        this.moneyBook = moneyBook;
    }
    public Date getDate() {
        return this.date;
    }
    
    public void setDate(Date date) {
        this.date = date;
    }
    public Double getCredit() {
        return this.credit;
    }
    
    public void setCredit(Double credit) {
        this.credit = credit;
    }
    public String getSms() {
        return this.sms;
    }
    
    public void setSms(String sms) {
        this.sms = sms;
    }




}


