package pojo;
// Generated Aug 2, 2017 11:22:50 AM by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * Lost generated by hbm2java
 */
public class Lost  implements java.io.Serializable {


     private Integer id;
     private GrnLog grnLog;
     private Double amount;
     private Date date;

    public Lost() {
    }

	
    public Lost(GrnLog grnLog) {
        this.grnLog = grnLog;
    }
    public Lost(GrnLog grnLog, Double amount, Date date) {
       this.grnLog = grnLog;
       this.amount = amount;
       this.date = date;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public GrnLog getGrnLog() {
        return this.grnLog;
    }
    
    public void setGrnLog(GrnLog grnLog) {
        this.grnLog = grnLog;
    }
    public Double getAmount() {
        return this.amount;
    }
    
    public void setAmount(Double amount) {
        this.amount = amount;
    }
    public Date getDate() {
        return this.date;
    }
    
    public void setDate(Date date) {
        this.date = date;
    }




}


