package pojo;
// Generated Aug 2, 2017 11:22:50 AM by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * ProductionLogBottle generated by hbm2java
 */
public class ProductionLogBottle  implements java.io.Serializable {


     private Integer id;
     private GrnLog grnLog;
     private Product productByBottleProductId;
     private Product productByProductId;
     private Double productQty;
     private Double btlQuantity;
     private Double costPerBottle;
     private Double labelCost;
     private Double otherCosts;
     private Double productPrice;
     private Date date;

    public ProductionLogBottle() {
    }

	
    public ProductionLogBottle(GrnLog grnLog, Product productByBottleProductId, Product productByProductId) {
        this.grnLog = grnLog;
        this.productByBottleProductId = productByBottleProductId;
        this.productByProductId = productByProductId;
    }
    public ProductionLogBottle(GrnLog grnLog, Product productByBottleProductId, Product productByProductId, Double productQty, Double btlQuantity, Double costPerBottle, Double labelCost, Double otherCosts, Double productPrice, Date date) {
       this.grnLog = grnLog;
       this.productByBottleProductId = productByBottleProductId;
       this.productByProductId = productByProductId;
       this.productQty = productQty;
       this.btlQuantity = btlQuantity;
       this.costPerBottle = costPerBottle;
       this.labelCost = labelCost;
       this.otherCosts = otherCosts;
       this.productPrice = productPrice;
       this.date = date;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public GrnLog getGrnLog() {
        return this.grnLog;
    }
    
    public void setGrnLog(GrnLog grnLog) {
        this.grnLog = grnLog;
    }
    public Product getProductByBottleProductId() {
        return this.productByBottleProductId;
    }
    
    public void setProductByBottleProductId(Product productByBottleProductId) {
        this.productByBottleProductId = productByBottleProductId;
    }
    public Product getProductByProductId() {
        return this.productByProductId;
    }
    
    public void setProductByProductId(Product productByProductId) {
        this.productByProductId = productByProductId;
    }
    public Double getProductQty() {
        return this.productQty;
    }
    
    public void setProductQty(Double productQty) {
        this.productQty = productQty;
    }
    public Double getBtlQuantity() {
        return this.btlQuantity;
    }
    
    public void setBtlQuantity(Double btlQuantity) {
        this.btlQuantity = btlQuantity;
    }
    public Double getCostPerBottle() {
        return this.costPerBottle;
    }
    
    public void setCostPerBottle(Double costPerBottle) {
        this.costPerBottle = costPerBottle;
    }
    public Double getLabelCost() {
        return this.labelCost;
    }
    
    public void setLabelCost(Double labelCost) {
        this.labelCost = labelCost;
    }
    public Double getOtherCosts() {
        return this.otherCosts;
    }
    
    public void setOtherCosts(Double otherCosts) {
        this.otherCosts = otherCosts;
    }
    public Double getProductPrice() {
        return this.productPrice;
    }
    
    public void setProductPrice(Double productPrice) {
        this.productPrice = productPrice;
    }
    public Date getDate() {
        return this.date;
    }
    
    public void setDate(Date date) {
        this.date = date;
    }




}


