package pojo;
// Generated Aug 2, 2017 11:22:50 AM by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * ProductionLogMix generated by hbm2java
 */
public class ProductionLogMix  implements java.io.Serializable {


     private Integer id;
     private GrnLog grnLog;
     private Product productByProduct1;
     private Product productByProduct2;
     private Double product1Quantity;
     private Double product2Quantity;
     private Date date;
     private Double quantity;
     private Double averagePrice;

    public ProductionLogMix() {
    }

	
    public ProductionLogMix(GrnLog grnLog, Product productByProduct1, Product productByProduct2) {
        this.grnLog = grnLog;
        this.productByProduct1 = productByProduct1;
        this.productByProduct2 = productByProduct2;
    }
    public ProductionLogMix(GrnLog grnLog, Product productByProduct1, Product productByProduct2, Double product1Quantity, Double product2Quantity, Date date, Double quantity, Double averagePrice) {
       this.grnLog = grnLog;
       this.productByProduct1 = productByProduct1;
       this.productByProduct2 = productByProduct2;
       this.product1Quantity = product1Quantity;
       this.product2Quantity = product2Quantity;
       this.date = date;
       this.quantity = quantity;
       this.averagePrice = averagePrice;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public GrnLog getGrnLog() {
        return this.grnLog;
    }
    
    public void setGrnLog(GrnLog grnLog) {
        this.grnLog = grnLog;
    }
    public Product getProductByProduct1() {
        return this.productByProduct1;
    }
    
    public void setProductByProduct1(Product productByProduct1) {
        this.productByProduct1 = productByProduct1;
    }
    public Product getProductByProduct2() {
        return this.productByProduct2;
    }
    
    public void setProductByProduct2(Product productByProduct2) {
        this.productByProduct2 = productByProduct2;
    }
    public Double getProduct1Quantity() {
        return this.product1Quantity;
    }
    
    public void setProduct1Quantity(Double product1Quantity) {
        this.product1Quantity = product1Quantity;
    }
    public Double getProduct2Quantity() {
        return this.product2Quantity;
    }
    
    public void setProduct2Quantity(Double product2Quantity) {
        this.product2Quantity = product2Quantity;
    }
    public Date getDate() {
        return this.date;
    }
    
    public void setDate(Date date) {
        this.date = date;
    }
    public Double getQuantity() {
        return this.quantity;
    }
    
    public void setQuantity(Double quantity) {
        this.quantity = quantity;
    }
    public Double getAveragePrice() {
        return this.averagePrice;
    }
    
    public void setAveragePrice(Double averagePrice) {
        this.averagePrice = averagePrice;
    }




}


