package pojo;
// Generated Aug 2, 2017 11:22:50 AM by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * RouteDebit generated by hbm2java
 */
public class RouteDebit  implements java.io.Serializable {


     private Integer id;
     private MoneyBook moneyBook;
     private RouteReg routeReg;
     private Date date;
     private Double debit;

    public RouteDebit() {
    }

	
    public RouteDebit(MoneyBook moneyBook, RouteReg routeReg) {
        this.moneyBook = moneyBook;
        this.routeReg = routeReg;
    }
    public RouteDebit(MoneyBook moneyBook, RouteReg routeReg, Date date, Double debit) {
       this.moneyBook = moneyBook;
       this.routeReg = routeReg;
       this.date = date;
       this.debit = debit;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public MoneyBook getMoneyBook() {
        return this.moneyBook;
    }
    
    public void setMoneyBook(MoneyBook moneyBook) {
        this.moneyBook = moneyBook;
    }
    public RouteReg getRouteReg() {
        return this.routeReg;
    }
    
    public void setRouteReg(RouteReg routeReg) {
        this.routeReg = routeReg;
    }
    public Date getDate() {
        return this.date;
    }
    
    public void setDate(Date date) {
        this.date = date;
    }
    public Double getDebit() {
        return this.debit;
    }
    
    public void setDebit(Double debit) {
        this.debit = debit;
    }




}


