/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package v;

import Backup.ObjectGenarater;

/**
 *
 * @author suhada
 */
public class backup extends javax.swing.JPanel {

    /**
     * Creates new form Backup
     */
    private backup() {
        initComponents();
        backup = ObjectGenarater.getBackup();
    }
    
    private static backup Backup;
    public static backup getInstance(){
        if(Backup==null)Backup=new backup();
        return Backup;
    }
    Backup.Backup backup;
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnBrowes = new com.alee.laf.button.WebButton();
        btnBackup = new com.alee.laf.button.WebButton();
        txtPath = new com.alee.laf.text.WebTextField();
        webLabel1 = new com.alee.laf.label.WebLabel();

        btnBrowes.setText("Browse");
        btnBrowes.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        btnBrowes.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                btnBrowesMouseReleased(evt);
            }
        });

        btnBackup.setText("Backup Now");
        btnBackup.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        btnBackup.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                btnBackupMouseReleased(evt);
            }
        });

        webLabel1.setText("Backup Path :");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btnBackup, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(webLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(txtPath, javax.swing.GroupLayout.PREFERRED_SIZE, 265, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnBrowes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(57, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(64, 64, 64)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtPath, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(webLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnBrowes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnBackup, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(129, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnBrowesMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnBrowesMouseReleased
        // TODO add your handling code here:
        backup.chooseFolder(txtPath, v.Home.getInstance());
    }//GEN-LAST:event_btnBrowesMouseReleased

    private void btnBackupMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnBackupMouseReleased
        // TODO add your handling code here:
        backup.getBackup(txtPath, v.Home.getInstance());
    }//GEN-LAST:event_btnBackupMouseReleased


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private com.alee.laf.button.WebButton btnBackup;
    private com.alee.laf.button.WebButton btnBrowes;
    private com.alee.laf.text.WebTextField txtPath;
    private com.alee.laf.label.WebLabel webLabel1;
    // End of variables declaration//GEN-END:variables
}
