/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package v;

import c.DebitCashTable;
import c.Errormzg;
import com.toedter.calendar.JDateChooser;
import java.awt.event.KeyEvent;
import java.util.Date;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.JTextField;
import javax.swing.table.DefaultTableModel;
import pojo.RouteReg;
import sun.security.krb5.internal.rcache.DflCache;

/**
 *
 * @author User
 */
public class DebitCash extends javax.swing.JFrame {

    /**
     * Creates new form DebitCash
     */
    public DebitCash() {
        initComponents();
    }
    static String date = null;
    RouteReg routeReg = null;
    int cashType = 0;
    JDateChooser dateChooserD = null;
    JTextField routeDebitIdD = null;
    JTextField routeRegisterIdD = null;
    //JTextField routeDebitD = null;
    JPanel jPanelD = null;

    private void clear() {
        tf_checkNumber.setText(null);
        tf_checkAmount.setText(null);
        tf_totalDebitPay.setText(null);
        c.CashChequeBookListner.getInstance().loadBankToCombo(cb_bankName);
        rb_cash.setSelected(true);
    }
    JPanel delivery1 = null;

    public void setDelivery(JPanel delivery) {
        this.delivery1 = delivery;

    }

    public DebitCash(JDateChooser dateChooser, JTextField routeRegisterId, JPanel delivery) {

        dateChooserD = dateChooser;
        //routeDebitIdD = routeDebitId;
        routeRegisterIdD = routeRegisterId;
        //routeDebitD = routeDebit;
        jPanelD = delivery;
        initComponents();
        //date = dateChooser.getDate().toString();
        //System.out.println("date "+ date);
        c.CashChequeBookListner.getInstance().loadBankToCombo(cb_bankName);
        routeReg = new m.RouteReg().getBy(Integer.parseInt(routeRegisterId.getText()));
        //System.out.println("RouteReg Credit l"+ routeReg.getCurrentCredit());
        tf_routeName.setText(routeReg.getName());
        tf_routeCredit.setText(String.valueOf(routeReg.getCurrentCredit()));
        rb_cash.setSelected(true);
        System.out.println("Route Register id :" + routeRegisterIdD.getText());
        dc_checkDate.setDate(new Date());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        rb_check = new javax.swing.JRadioButton();
        rb_cash = new javax.swing.JRadioButton();
        jLabel3 = new javax.swing.JLabel();
        tf_checkNumber = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        cb_bankName = new javax.swing.JComboBox<>();
        jLabel5 = new javax.swing.JLabel();
        tf_checkAmount = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        tf_routeName = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        tf_routeCredit = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        tf_totalDebitPay = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbl_debitCheckList = new javax.swing.JTable();
        btn_saverouteDebit = new javax.swing.JButton();
        btn_clearRouteDebit = new javax.swing.JButton();
        btn_removeRow = new javax.swing.JButton();
        dc_checkDate = new com.toedter.calendar.JDateChooser();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                jPanel1MouseReleased(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel1.setText("Payment Method");

        rb_check.setBackground(new java.awt.Color(255, 255, 255));
        buttonGroup1.add(rb_check);
        rb_check.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        rb_check.setText("Check");
        rb_check.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                rb_checkStateChanged(evt);
            }
        });

        rb_cash.setBackground(new java.awt.Color(255, 255, 255));
        buttonGroup1.add(rb_cash);
        rb_cash.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        rb_cash.setText("Cash");
        rb_cash.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                rb_cashStateChanged(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel3.setText("Check Number");

        tf_checkNumber.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel4.setText("Bank");

        cb_bankName.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel5.setText("Check Amount");

        tf_checkAmount.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        tf_checkAmount.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tf_checkAmountActionPerformed(evt);
            }
        });
        tf_checkAmount.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                tf_checkAmountKeyTyped(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel6.setText("Route Name");

        tf_routeName.setEditable(false);
        tf_routeName.setBackground(new java.awt.Color(255, 255, 255));
        tf_routeName.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel7.setText("Route Credit");

        tf_routeCredit.setEditable(false);
        tf_routeCredit.setBackground(new java.awt.Color(255, 255, 255));
        tf_routeCredit.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        jLabel8.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel8.setText("Total Amount");

        tf_totalDebitPay.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        tf_totalDebitPay.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tf_totalDebitPayActionPerformed(evt);
            }
        });
        tf_totalDebitPay.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                tf_totalDebitPayKeyTyped(evt);
            }
        });

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));

        tbl_debitCheckList.setRowHeight(25);
        tbl_debitCheckList.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        tbl_debitCheckList.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Check Date", "Check Number", "Bank", "Check Amount"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tbl_debitCheckList);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 651, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1)
                .addContainerGap())
        );

        btn_saverouteDebit.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btn_saverouteDebit.setText("save");
        btn_saverouteDebit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                btn_saverouteDebitMouseReleased(evt);
            }
        });
        btn_saverouteDebit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_saverouteDebitActionPerformed(evt);
            }
        });

        btn_clearRouteDebit.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btn_clearRouteDebit.setText("clear");
        btn_clearRouteDebit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                btn_clearRouteDebitMouseReleased(evt);
            }
        });

        btn_removeRow.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btn_removeRow.setText("remove check from table");
        btn_removeRow.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                btn_removeRowMouseReleased(evt);
            }
        });

        dc_checkDate.setDateFormatString("yyyy-MM-dd");
        dc_checkDate.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel2.setText("Check Date");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btn_saverouteDebit, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btn_clearRouteDebit, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btn_removeRow, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4)
                            .addComponent(jLabel5)
                            .addComponent(jLabel8)
                            .addComponent(jLabel2))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(cb_bankName, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(tf_checkAmount)
                            .addComponent(tf_totalDebitPay)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addComponent(rb_cash)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(rb_check))
                            .addComponent(tf_checkNumber)
                            .addComponent(dc_checkDate, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(205, 205, 205)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel6)
                                .addGap(18, 18, 18)
                                .addComponent(tf_routeName, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel7)
                                .addGap(18, 18, 18)
                                .addComponent(tf_routeCredit, javax.swing.GroupLayout.PREFERRED_SIZE, 199, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addContainerGap(205, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 682, Short.MAX_VALUE))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(rb_check)
                    .addComponent(jLabel6)
                    .addComponent(tf_routeName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(rb_cash))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel7)
                        .addComponent(tf_routeCredit, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(jLabel2)
                        .addComponent(dc_checkDate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(tf_checkNumber, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(cb_bankName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(tf_checkAmount, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(22, 22, 22)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel8)
                            .addComponent(tf_totalDebitPay, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(48, 48, 48)
                        .addComponent(btn_saverouteDebit)
                        .addGap(18, 18, 18)
                        .addComponent(btn_clearRouteDebit)
                        .addGap(18, 18, 18)
                        .addComponent(btn_removeRow))
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jPanel1MouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel1MouseReleased
        // TODO add your handling code here:

    }//GEN-LAST:event_jPanel1MouseReleased

    private void rb_cashStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_rb_cashStateChanged
        // TODO add your handling code here:
        if (rb_cash.isSelected()) {
            cashType = 1;
            tf_checkNumber.setEnabled(false);
            //tf_checkNumber.setVisible(false);
            //tf_checkNumber.setVisible(false);
            cb_bankName.setEnabled(false);
            tf_checkAmount.setEnabled(false);
            //tf_totalDebitPay.setText(String.valueOf(cashType));
        } else {

            //tf_checkNumber.setVisible(true);
            tf_checkNumber.setEnabled(true);
            cb_bankName.setEnabled(true);
            tf_checkAmount.setEnabled(true);
            //tf_checkNumber.setVisible(true);
        }
    }//GEN-LAST:event_rb_cashStateChanged

    private void rb_checkStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_rb_checkStateChanged
        // TODO add your handling code here:
        if (rb_check.isSelected()) {
            cashType = 2;
            //tf_totalDebitPay.setText(String.valueOf(cashType));
        }
    }//GEN-LAST:event_rb_checkStateChanged

    private void btn_saverouteDebitMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_saverouteDebitMouseReleased
        // TODO add your handling code here:
        try {
            if (tf_totalDebitPay.getText().isEmpty()) {
                Errormzg.displayerrorMessage("Enter an amount");
            } else {
                double rcREDIT = Double.parseDouble(tf_routeCredit.getText());
                double rcDebitPay = Double.parseDouble(tf_totalDebitPay.getText());
                if (rcDebitPay > rcREDIT) {
                    JOptionPane.showMessageDialog(rootPane, "Please enter a value less than or equal to Route Credit", "Debit Pay", JOptionPane.OK_OPTION);
                } else {

                    new c.RouteDebitMoneyBook().routeDebitMoneyBookSave(cashType, dateChooserD, tf_totalDebitPay, routeReg, rootPane, tbl_debitCheckList, tf_checkNumber, cb_bankName, tf_checkAmount, dc_checkDate);
                    tf_routeCredit.setText(String.valueOf(routeReg.getCurrentCredit()));

                    JOptionPane.showMessageDialog(null, "Data Saved");

                    v.Delivery.getInstance().clearRouteDebit();
                    this.dispose();

                }
            }
        } catch (Exception e) {
            e.printStackTrace();
        }


    }//GEN-LAST:event_btn_saverouteDebitMouseReleased

    private void btn_clearRouteDebitMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_clearRouteDebitMouseReleased
        // TODO add your handling code here:
        //JOptionPane.showConfirmDialog(rootPane, "srgdgd");
        clear();
    }//GEN-LAST:event_btn_clearRouteDebitMouseReleased

    private void tf_totalDebitPayActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tf_totalDebitPayActionPerformed
        // TODO add your handling code here:
        btn_saverouteDebit.requestFocus();
    }//GEN-LAST:event_tf_totalDebitPayActionPerformed

    private void tf_checkAmountActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tf_checkAmountActionPerformed
        // TODO add your handling code here:

        try {
            double rcREDIT = Double.parseDouble(tf_routeCredit.getText());
            rcREDIT = (Math.round(rcREDIT * 100.0) / 100.0);
            double rcDebitPay = Double.parseDouble(tf_checkAmount.getText());
            rcDebitPay = (Math.round(rcDebitPay * 100.0) / 100.0);
            if (rcDebitPay > rcREDIT) {
                JOptionPane.showMessageDialog(rootPane, "Please enter a value less than or equal to Route Credit", "Debit Pay", JOptionPane.OK_OPTION);
            } else {
                if (cb_bankName.getSelectedIndex() != 0) {
                    new DebitCashTable().setDebitCashTable(tf_checkNumber, cb_bankName, tf_checkAmount, tbl_debitCheckList,dc_checkDate);
                    new DebitCashTable().tableTotal(tf_totalDebitPay, tbl_debitCheckList);
                } else {
                    Errormzg.displayerrorMessage("Please select a Bank");
                }

            }
//        tf_checkNumber.setText(null);
//        tf_checkAmount.setText(null);
//        cb_bankName.setSelectedIndex(0);
//        tf_checkNumber.requestFocus();
            tf_checkAmount.setText(null);
            tf_checkNumber.requestFocus();
            tf_checkNumber.setText(null);
        } catch (Exception e) {
            e.printStackTrace();
        }
    }//GEN-LAST:event_tf_checkAmountActionPerformed

    private void tf_checkAmountKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tf_checkAmountKeyTyped
        // TODO add your handling code here:
        char vChar = evt.getKeyChar();
        if (!(Character.isDigit(vChar)
                || (vChar == KeyEvent.VK_BACK_SPACE)
                || (vChar == KeyEvent.VK_DELETE) || vChar == KeyEvent.VK_PERIOD)) {
            evt.consume();
        }
    }//GEN-LAST:event_tf_checkAmountKeyTyped

    private void tf_totalDebitPayKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tf_totalDebitPayKeyTyped
        // TODO add your handling code here:
        char vChar = evt.getKeyChar();
        if (!(Character.isDigit(vChar)
                || (vChar == KeyEvent.VK_BACK_SPACE)
                || (vChar == KeyEvent.VK_DELETE) || vChar == KeyEvent.VK_PERIOD)) {
            evt.consume();
        }
    }//GEN-LAST:event_tf_totalDebitPayKeyTyped

    private void btn_removeRowMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_removeRowMouseReleased
        // TODO add your handling code here:
        try {
            DefaultTableModel dtm = (DefaultTableModel) tbl_debitCheckList.getModel();
            dtm.removeRow(tbl_debitCheckList.getSelectedRow());
            new DebitCashTable().tableTotal(tf_totalDebitPay, tbl_debitCheckList);
        } catch (Exception e) {
            e.printStackTrace();
        }
        //new DebitCashTable().tableTotal(tf_totalDebitPay, tbl_debitCheckList);
    }//GEN-LAST:event_btn_removeRowMouseReleased

    private void btn_saverouteDebitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_saverouteDebitActionPerformed
        // TODO add your handling code here:
//        if (tf_totalDebitPay.getText().isEmpty()) {
//            Errormzg.displayerrorMessage("Enter an amount");
//        } else {
//            double rcREDIT = Double.parseDouble(tf_routeCredit.getText());
//            double rcDebitPay = Double.parseDouble(tf_totalDebitPay.getText());
//            if (rcDebitPay > rcREDIT) {
//                JOptionPane.showMessageDialog(rootPane, "Please enter a value less than or equal to Route Credit", "Debit Pay", JOptionPane.OK_OPTION);
//            } else {
//
//                new c.RouteDebitMoneyBook().routeDebitMoneyBookSave(cashType, dateChooserD, tf_totalDebitPay, routeReg, routeDebitIdD, rootPane, tbl_debitCheckList, tf_checkNumber, cb_bankName, tf_checkAmount);
//                tf_routeCredit.setText(String.valueOf(routeReg.getCurrentCredit()));
//                JOptionPane.showMessageDialog(null, "Data Saved");
//                this.dispose();
//
//            }
//        }
    }//GEN-LAST:event_btn_saverouteDebitActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DebitCash.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DebitCash.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DebitCash.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DebitCash.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new DebitCash().setVisible(true);
            }
        });

    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_clearRouteDebit;
    private javax.swing.JButton btn_removeRow;
    private javax.swing.JButton btn_saverouteDebit;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JComboBox<String> cb_bankName;
    private com.toedter.calendar.JDateChooser dc_checkDate;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JRadioButton rb_cash;
    private javax.swing.JRadioButton rb_check;
    private javax.swing.JTable tbl_debitCheckList;
    private javax.swing.JTextField tf_checkAmount;
    private javax.swing.JTextField tf_checkNumber;
    private javax.swing.JTextField tf_routeCredit;
    private javax.swing.JTextField tf_routeName;
    private javax.swing.JTextField tf_totalDebitPay;
    // End of variables declaration//GEN-END:variables
}
