/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package v;

import c.AssetControl;
import c.AutoComplete;
import c.DeliveryInvoice;
import java.awt.Color;
import java.awt.event.KeyEvent;
import java.io.File;
import java.io.FileWriter;
import java.io.IOException;
import java.nio.file.Files;
import java.nio.file.Path;
import java.nio.file.Paths;
import java.util.Date;
import javax.swing.JOptionPane;
import javax.swing.JTabbedPane;
import javax.swing.JTable;
import javax.swing.JTextField;
import m.DeliverDetail;
import m.ValueValidation;
import pojo.Customer;
import static v.frmDeleverySummery.tpDelivery;

/**
 *
 * @author Buddhika Prasanna
 */
public class frmDeliveryInvoice extends javax.swing.JFrame {

    static JTable tblDI;
    static JTabbedPane tpDelivery;
    static JTextField txtRouteIdDI;
    AutoComplete ac;
    ValueValidation validation;

    /**
     * Creates new form frmDeliveryInvoice
     *
     * @param tblDI
     * @param txtRouteIdDI
     * @param tpDelivery
     */
    public frmDeliveryInvoice(JTable tblDI, JTextField txtRouteIdDI, JTabbedPane tpDelivery) {
        initComponents();
        validation = new ValueValidation();
        ac = new AutoComplete();
        ac.autoCompleteBankName(txtBank);
        ac.autoCompleteCustomerName(txtCusName);
        frmDeliveryInvoice.tblDI = tblDI;
        frmDeliveryInvoice.txtRouteIdDI = txtRouteIdDI;
        frmDeliveryInvoice.tpDelivery = tpDelivery;
        dcSaleDate.setDate(new Date());
        calInvoiceAmount();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel3 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        dcSaleDate = new com.toedter.calendar.JDateChooser();
        txtInvoiceAmount = new javax.swing.JTextField();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jPanel6 = new javax.swing.JPanel();
        txtCusId = new javax.swing.JTextField();
        txtCusName = new javax.swing.JTextField();
        txtCurrentCrdit = new javax.swing.JTextField();
        jPanel9 = new javax.swing.JPanel();
        jPanel10 = new javax.swing.JPanel();
        jLabel15 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        txtBank = new javax.swing.JTextField();
        jLabel18 = new javax.swing.JLabel();
        txtCheckAmount = new javax.swing.JTextField();
        btnAdd = new javax.swing.JButton();
        txtChequeNimber = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        dcReturnDate = new com.toedter.calendar.JDateChooser();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblCheck = new javax.swing.JTable();
        jPanel8 = new javax.swing.JPanel();
        btnBack = new javax.swing.JButton();
        btnSave = new javax.swing.JButton();
        jPanel13 = new javax.swing.JPanel();
        jPanel12 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jPanel11 = new javax.swing.JPanel();
        txtCashPay = new javax.swing.JTextField();
        txtChequePay = new javax.swing.JTextField();
        txtDeuAMount = new javax.swing.JTextField();
        txtBalance = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setResizable(false);
        setType(java.awt.Window.Type.UTILITY);

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createMatteBorder(1, 0, 1, 0, new java.awt.Color(102, 102, 255)), "Invoice Details", javax.swing.border.TitledBorder.LEFT, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 14), new java.awt.Color(51, 51, 255))); // NOI18N

        jPanel2.setLayout(new java.awt.GridLayout(3, 0, 5, 5));

        dcSaleDate.setDateFormatString("yyyy-MM-dd");
        dcSaleDate.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jPanel2.add(dcSaleDate);

        txtInvoiceAmount.setBackground(new java.awt.Color(240, 240, 240));
        txtInvoiceAmount.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        txtInvoiceAmount.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        txtInvoiceAmount.setText("0");
        txtInvoiceAmount.setToolTipText("");
        txtInvoiceAmount.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(102, 102, 255)));
        jPanel2.add(txtInvoiceAmount);

        jPanel1.setLayout(new java.awt.GridLayout(3, 0, 5, 5));

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel1.setText("Sale Date");
        jPanel1.add(jLabel1);

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel2.setText("Invoice Amount");
        jPanel1.add(jLabel2);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, 91, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel5.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createMatteBorder(1, 0, 1, 0, new java.awt.Color(102, 102, 255)), "Customer Details", javax.swing.border.TitledBorder.LEFT, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 14), new java.awt.Color(51, 51, 255))); // NOI18N

        jPanel4.setLayout(new java.awt.GridLayout(3, 0, 5, 5));

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel4.setText("Customer Id");
        jPanel4.add(jLabel4);

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel5.setText("Customer Name");
        jPanel4.add(jLabel5);

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel7.setText("Current Credit");
        jPanel4.add(jLabel7);

        jPanel6.setLayout(new java.awt.GridLayout(3, 0, 5, 5));

        txtCusId.setBackground(new java.awt.Color(240, 240, 240));
        txtCusId.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txtCusId.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(102, 102, 255)));
        jPanel6.add(txtCusId);

        txtCusName.setBackground(new java.awt.Color(240, 240, 240));
        txtCusName.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txtCusName.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(102, 102, 255)));
        txtCusName.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtCusNameFocusGained(evt);
            }
        });
        txtCusName.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtCusNameKeyTyped(evt);
            }
        });
        jPanel6.add(txtCusName);

        txtCurrentCrdit.setBackground(new java.awt.Color(240, 240, 240));
        txtCurrentCrdit.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        txtCurrentCrdit.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        txtCurrentCrdit.setText("0");
        txtCurrentCrdit.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(102, 102, 255)));
        jPanel6.add(txtCurrentCrdit);

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, 226, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, 88, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel9.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createMatteBorder(1, 0, 1, 0, new java.awt.Color(153, 153, 255)), "Cheque Payment", javax.swing.border.TitledBorder.RIGHT, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 15), new java.awt.Color(51, 51, 255))); // NOI18N

        jLabel15.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel15.setText("Cheque Number");

        jLabel17.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel17.setText("Bank Name");

        txtBank.setBackground(new java.awt.Color(240, 240, 240));
        txtBank.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txtBank.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(51, 153, 255)));
        txtBank.setNextFocusableComponent(txtCheckAmount);
        txtBank.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtBankKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtBankKeyTyped(evt);
            }
        });

        jLabel18.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel18.setText("Amount");

        txtCheckAmount.setBackground(new java.awt.Color(240, 240, 240));
        txtCheckAmount.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txtCheckAmount.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        txtCheckAmount.setText("0");
        txtCheckAmount.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(51, 153, 255)));
        txtCheckAmount.setNextFocusableComponent(btnAdd);
        txtCheckAmount.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtCheckAmountFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtCheckAmountFocusLost(evt);
            }
        });
        txtCheckAmount.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtCheckAmountKeyTyped(evt);
            }
        });

        btnAdd.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        btnAdd.setText("Add");
        btnAdd.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                btnAddMouseReleased(evt);
            }
        });

        txtChequeNimber.setBackground(new java.awt.Color(240, 240, 240));
        txtChequeNimber.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txtChequeNimber.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(51, 153, 255)));
        txtChequeNimber.setNextFocusableComponent(dcReturnDate);

        jLabel16.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel16.setText("Return Date");

        dcReturnDate.setDateFormatString("yyyy-MM-dd");
        dcReturnDate.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        javax.swing.GroupLayout jPanel10Layout = new javax.swing.GroupLayout(jPanel10);
        jPanel10.setLayout(jPanel10Layout);
        jPanel10Layout.setHorizontalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel10Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel15)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(txtChequeNimber, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel16)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(dcReturnDate, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel17)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(txtBank, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel18)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(txtCheckAmount, javax.swing.GroupLayout.DEFAULT_SIZE, 167, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addComponent(btnAdd))
        );
        jPanel10Layout.setVerticalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(btnAdd, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel10Layout.createSequentialGroup()
                .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel10Layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(dcReturnDate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(1, 1, 1))
                    .addGroup(jPanel10Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel15)
                            .addComponent(jLabel17)
                            .addComponent(txtBank, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtCheckAmount, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtChequeNimber, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel16)
                            .addComponent(jLabel18, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap(22, Short.MAX_VALUE))
        );

        tblCheck.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        tblCheck.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Cheque Number", "Bank Name", "Amount", "Return Date"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblCheck.getTableHeader().setReorderingAllowed(false);
        tblCheck.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                tblCheckKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                tblCheckKeyTyped(evt);
            }
        });
        jScrollPane2.setViewportView(tblCheck);
        if (tblCheck.getColumnModel().getColumnCount() > 0) {
            tblCheck.getColumnModel().getColumn(0).setResizable(false);
            tblCheck.getColumnModel().getColumn(1).setResizable(false);
            tblCheck.getColumnModel().getColumn(2).setResizable(false);
            tblCheck.getColumnModel().getColumn(3).setResizable(false);
            tblCheck.getColumnModel().getColumn(3).setPreferredWidth(10);
        }

        javax.swing.GroupLayout jPanel9Layout = new javax.swing.GroupLayout(jPanel9);
        jPanel9.setLayout(jPanel9Layout);
        jPanel9Layout.setHorizontalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jScrollPane2)))
        );
        jPanel9Layout.setVerticalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 137, Short.MAX_VALUE)
                .addContainerGap())
        );

        jPanel8.setLayout(new java.awt.GridLayout(1, 0, 10, 10));

        btnBack.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btnBack.setText("Back");
        btnBack.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                btnBackMouseReleased(evt);
            }
        });
        jPanel8.add(btnBack);

        btnSave.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btnSave.setText("Save");
        btnSave.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                btnSaveMouseReleased(evt);
            }
        });
        jPanel8.add(btnSave);

        jPanel13.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createMatteBorder(1, 0, 1, 0, new java.awt.Color(102, 102, 255)), "Payment Summery", javax.swing.border.TitledBorder.RIGHT, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 14), new java.awt.Color(51, 51, 255))); // NOI18N

        jPanel12.setLayout(new java.awt.GridLayout(4, 0, 5, 5));

        jLabel8.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel8.setText("Cash Pay Amount");
        jPanel12.add(jLabel8);

        jLabel9.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel9.setText("Cheque Pay Amount");
        jPanel12.add(jLabel9);

        jLabel10.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel10.setText("Deu Amount");
        jPanel12.add(jLabel10);

        jLabel11.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel11.setText("Balance");
        jPanel12.add(jLabel11);

        jPanel11.setLayout(new java.awt.GridLayout(4, 0, 5, 5));

        txtCashPay.setBackground(new java.awt.Color(240, 240, 240));
        txtCashPay.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        txtCashPay.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        txtCashPay.setText("0");
        txtCashPay.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(102, 102, 255)));
        txtCashPay.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtCashPayFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtCashPayFocusLost(evt);
            }
        });
        txtCashPay.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtCashPayKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtCashPayKeyTyped(evt);
            }
        });
        jPanel11.add(txtCashPay);

        txtChequePay.setBackground(new java.awt.Color(240, 240, 240));
        txtChequePay.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        txtChequePay.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        txtChequePay.setText("0");
        txtChequePay.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(102, 102, 255)));
        jPanel11.add(txtChequePay);

        txtDeuAMount.setBackground(new java.awt.Color(240, 240, 240));
        txtDeuAMount.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        txtDeuAMount.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        txtDeuAMount.setText("0");
        txtDeuAMount.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(102, 102, 255)));
        jPanel11.add(txtDeuAMount);

        txtBalance.setBackground(new java.awt.Color(240, 240, 240));
        txtBalance.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        txtBalance.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        txtBalance.setText("0");
        txtBalance.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(102, 102, 255)));
        jPanel11.add(txtBalance);

        javax.swing.GroupLayout jPanel13Layout = new javax.swing.GroupLayout(jPanel13);
        jPanel13.setLayout(jPanel13Layout);
        jPanel13Layout.setHorizontalGroup(
            jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel13Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel12, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jPanel11, javax.swing.GroupLayout.PREFERRED_SIZE, 202, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel13Layout.setVerticalGroup(
            jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel13Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel11, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel12, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jPanel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jPanel13, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jPanel8, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 400, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jPanel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel13, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel8, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void calInvoiceAmount() {
        try {
            double tot = 0.0;
            for (int i = 0; i < tblDI.getRowCount(); i++) {
                tot += Double.parseDouble(tblDI.getValueAt(i, 4).toString());
            }
            txtInvoiceAmount.setText(String.valueOf(tot));
        } catch (Exception e) {
            e.printStackTrace();
        }
    }

    private void txtBankKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtBankKeyReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_txtBankKeyReleased

    private void txtBankKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtBankKeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_txtBankKeyTyped

    private void txtCheckAmountFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtCheckAmountFocusGained
        // TODO add your handling code here:
        if ("0".equals(txtCheckAmount.getText())) {
            txtCheckAmount.setText("");
        }
    }//GEN-LAST:event_txtCheckAmountFocusGained

    private void txtCheckAmountFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtCheckAmountFocusLost
        // TODO add your handling code here:
        if ("".equals(txtCheckAmount.getText())) {
            txtCheckAmount.setText("0");
        }
    }//GEN-LAST:event_txtCheckAmountFocusLost

    private void btnAddMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnAddMouseReleased
        // TODO add your handling code here:
        if (!txtChequeNimber.getText().isEmpty()) {
            if (!txtBank.getText().isEmpty()) {
                try {
                    double checkAmount = Double.parseDouble(txtChequePay.getText());
                    double Amount = Double.parseDouble(txtCheckAmount.getText());
                    checkAmount += Amount;
                    double checkAmount2 = Math.round(checkAmount * 100.0) / 100.0;
                    txtChequePay.setText(String.valueOf(checkAmount2));

                    double invoiceAmount = Double.parseDouble(txtInvoiceAmount.getText());
                    double cashAmount = Double.parseDouble(txtCashPay.getText());
                    double chequeAmount = Double.parseDouble(txtChequePay.getText());
                    double deuAmount = invoiceAmount - (cashAmount + chequeAmount);
                    double deuAmount2 = Math.round(deuAmount * 100.0) / 100.0;

                    txtDeuAMount.setText(String.valueOf(deuAmount2));

                } catch (Exception e) {
                    e.printStackTrace();
                }
                new DeliveryInvoice().addCheck(txtChequeNimber, txtBank, txtCheckAmount, dcReturnDate, tblCheck);
            }
        }
    }//GEN-LAST:event_btnAddMouseReleased

    private void tblCheckKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tblCheckKeyReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_tblCheckKeyReleased

    private void tblCheckKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tblCheckKeyTyped
        // TODO add your handling code here:
        if (evt.isControlDown() & evt.getKeyChar() == KeyEvent.VK_DELETE) {
            for (int i = 0; i < tblCheck.getRowCount(); i++) {
                double checkAmount = Double.parseDouble(txtChequePay.getText());
                double Amount = Double.parseDouble(tblCheck.getValueAt(i, 2).toString());
                checkAmount -= Amount;
                double deuAmount = Double.parseDouble(txtDeuAMount.getText());
                deuAmount += Amount;
                txtChequePay.setText(String.valueOf(checkAmount));
                txtDeuAMount.setText(String.valueOf(deuAmount));

            }
            new c.DeleveryItemTable().removeAllItem(tblCheck);
        } else if (evt.getKeyChar() == KeyEvent.VK_DELETE) {
            double checkAmount = Double.parseDouble(txtChequePay.getText());
            double Amount = Double.parseDouble(tblCheck.getValueAt(tblCheck.getSelectedRow(), 2).toString());
            checkAmount -= Amount;
            double deuAmount = Double.parseDouble(txtDeuAMount.getText());
            deuAmount += Amount;
            txtChequePay.setText(String.valueOf(checkAmount));
            txtDeuAMount.setText(String.valueOf(deuAmount));
            new c.DeleveryItemTable().removeItem(tblCheck);
        }
    }//GEN-LAST:event_tblCheckKeyTyped

    private void btnBackMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnBackMouseReleased
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_btnBackMouseReleased

    public void createReportDocs() {
        Path path = Paths.get("D:\\ReportDocs");
        //if directory exists?
        if (!Files.exists(path)) {
            try {
                Files.createDirectories(path);
            } catch (Exception e) {
                //fail to create directory
                e.printStackTrace();
            }
        } else {

        }
    }

    public void createFile() {
        String[] para = {""};
        try {
            File f = new File("Parameter.txt");
            if (f.exists()) {
                f.delete();
            }
            FileWriter writer = new FileWriter("D:\\ReportDocs\\Parameter.txt", true);
            writer.write(para[0]);
            writer.close();
        } catch (IOException e) {
            e.printStackTrace();
        }
    }

    private void btnSaveMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnSaveMouseReleased
        // TODO add your handling code here:
        if (txtCusId.getText().isEmpty() & txtCusId.getText().isEmpty()) {
            JOptionPane.showMessageDialog(rootPane, "Please enter valid customer", "Invoice Save", JOptionPane.WARNING_MESSAGE);
            txtCusName.requestFocus();
            txtCusName.setBackground(Color.red);
        } else {
            String payStatus = "Not Pay";
            if (txtDeuAMount.getText().equals("0.0") | txtDeuAMount.getText().equals("0")) {
                payStatus = "PAYED";
            } else {
                payStatus = "NOT PAYED";
            }
            DeliveryInvoice deliveryInvoice = new DeliveryInvoice();
            int saveInvoiceLog = deliveryInvoice.saveInvoiceLog(dcSaleDate, "payStatus", txtCusId, tblDI);
            if (saveInvoiceLog == 1) {
                deliveryInvoice.saveRouteDebit(dcSaleDate, "Deliver Cash", Double.parseDouble(txtCashPay.getText()), "Cash", "Deliver Cash", "Income", txtRouteIdDI);
                deliveryInvoice.saveCheck(dcSaleDate, txtRouteIdDI, txtCusId, tblCheck);
                if (Double.parseDouble(txtDeuAMount.getText()) > 0) {
                    deliveryInvoice.saveRouteCreit(dcSaleDate, Double.parseDouble(txtDeuAMount.getText()), txtRouteIdDI);
                    deliveryInvoice.saveCustomerCreit(dcSaleDate, Double.parseDouble(txtDeuAMount.getText()), txtCusId);
                    deliveryInvoice.getCustomerByCusName(txtCusName.getText());
                    deliveryInvoice.updateCustomerCreit(Double.parseDouble(txtDeuAMount.getText()));
                }
                if (Double.parseDouble(txtCurrentCrdit.getText()) > 0 & Double.parseDouble(txtBalance.getText()) > 0) {
                    int conform = JOptionPane.showConfirmDialog(rootPane, "You have a previos credit.Do you want to pay credit", "Credit Pay", JOptionPane.YES_NO_OPTION, JOptionPane.QUESTION_MESSAGE);
                    if (conform == 0) {
                        deliveryInvoice.getCustomerByCusName(txtCusName.getText());
                        String updateCustomerCreitPay = deliveryInvoice.updateCustomerCreitPay(dcSaleDate, "Customer Credit Pay", Double.parseDouble(txtBalance.getText()), "Cash", "Deliver Cash", "Income");
                        JOptionPane.showMessageDialog(rootPane, "Now, you pay youre credit.Credit is : " + updateCustomerCreitPay + " ", "Customer Credit Pay", JOptionPane.INFORMATION_MESSAGE);
                    }
                }

                AssetControl assetControl = AssetControl.getInstance();
                double amount = 0.0;
                double cashPay = Double.parseDouble(txtCashPay.getText());
                double balance = Double.parseDouble(txtBalance.getText());
                if (cashPay > balance) {
                    amount = cashPay - balance;
                } else {
                    amount = Double.parseDouble(txtCashPay.getText());
                }
                assetControl.updateCashAsset(Math.round(amount * 100.0) / 100.0, '+');
                JOptionPane.showMessageDialog(rootPane, "Receipt save successful", "Receipt Save", JOptionPane.INFORMATION_MESSAGE);
                tpDelivery.setSelectedIndex(3);

                try {
                    new c.VehicleReturn().addItem(DeliverDetail.getTxtVehicleIdVR(), DeliverDetail.getTxtRouteIdVR(), DeliverDetail.getDcDeleverDateVR(), DeliverDetail.getTblItemVR());
                } catch (Exception e) {
                    e.printStackTrace();
                }

                this.dispose();
            }
        }
    }//GEN-LAST:event_btnSaveMouseReleased

    private void txtCusNameKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtCusNameKeyTyped
        // TODO add your handling code here:
        if (evt.getKeyChar() == KeyEvent.VK_ENTER) {
            try {
                Customer customer = new c.DeliveryInvoice().getCustomerByCusName(txtCusName.getText());
                txtCusId.setText(String.valueOf(customer.getId()));
                txtCurrentCrdit.setText(String.valueOf(customer.getCredit()));
                txtCusName.setBackground(new Color(240, 240, 240));
            } catch (Exception e) {
                e.printStackTrace();
            }
        }
    }//GEN-LAST:event_txtCusNameKeyTyped

    private void txtCashPayFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtCashPayFocusGained
        // TODO add your handling code here:
        if ("0".equals(txtCashPay.getText())) {
            txtCashPay.setText("");
        }
    }//GEN-LAST:event_txtCashPayFocusGained

    private void txtCashPayFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtCashPayFocusLost
        // TODO add your handling code here:
        if ("".equals(txtCashPay.getText())) {
            txtCashPay.setText("0");
        }
    }//GEN-LAST:event_txtCashPayFocusLost

    private void txtCashPayKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtCashPayKeyTyped
        // TODO add your handling code here:
        char vChar = evt.getKeyChar();
        if (!(Character.isDigit(vChar) || (vChar == KeyEvent.VK_BACK_SPACE) || (vChar == KeyEvent.VK_DELETE) || vChar == KeyEvent.VK_PERIOD)) {
            evt.consume();
        }
    }//GEN-LAST:event_txtCashPayKeyTyped

    private void txtCashPayKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtCashPayKeyReleased
        // TODO add your handling code here:
        try {
            if (txtCashPay.getText().isEmpty()) {
                double invoiceAmount = Double.parseDouble(txtInvoiceAmount.getText());
                double cashAmount = 0.0;
                double chequeAmount = Double.parseDouble(txtChequePay.getText());
                double deuAmount = invoiceAmount - (cashAmount + chequeAmount);
                double deuAmount2 = Math.round(deuAmount * 100.0) / 100.0;

                if (deuAmount2 < 0) {
                    txtDeuAMount.setText("0.0");
                    txtBalance.setText(String.valueOf(deuAmount2 * -1));
                } else {
                    txtDeuAMount.setText(String.valueOf(deuAmount2));
                    txtBalance.setText("0.0");
                }
            } else {
                double invoiceAmount = Double.parseDouble(txtInvoiceAmount.getText());
                double cashAmount = Double.parseDouble(txtCashPay.getText());
                double chequeAmount = Double.parseDouble(txtChequePay.getText());
                double deuAmount = invoiceAmount - (cashAmount + chequeAmount);
                double deuAmount2 = Math.round(deuAmount * 100.0) / 100.0;

                if (deuAmount2 < 0) {
                    txtDeuAMount.setText("0.0");
                    txtBalance.setText(String.valueOf(deuAmount2 * -1));
                } else {
                    txtDeuAMount.setText(String.valueOf(deuAmount2));
                    txtBalance.setText("0.0");
                }
            }

        } catch (Exception e) {
            e.printStackTrace();
        }
    }//GEN-LAST:event_txtCashPayKeyReleased

    private void txtCheckAmountKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtCheckAmountKeyTyped
        // TODO add your handling code here:
        char vChar = evt.getKeyChar();
        if (!(Character.isDigit(vChar) || (vChar == KeyEvent.VK_BACK_SPACE) || (vChar == KeyEvent.VK_DELETE) || vChar == KeyEvent.VK_PERIOD)) {
            evt.consume();
        }
        if (evt.getKeyChar() == KeyEvent.VK_ENTER) {
            if (!txtChequeNimber.getText().isEmpty()) {
                if (!txtBank.getText().isEmpty()) {
                    try {
                        double checkAmount = Double.parseDouble(txtChequePay.getText());
                        double Amount = Double.parseDouble(txtCheckAmount.getText());
                        checkAmount += Amount;
                        double checkAmount2 = Math.round(checkAmount * 100.0) / 100.0;
                        txtChequePay.setText(String.valueOf(checkAmount2));

                        double invoiceAmount = Double.parseDouble(txtInvoiceAmount.getText());
                        double cashAmount = Double.parseDouble(txtCashPay.getText());
                        double chequeAmount = Double.parseDouble(txtChequePay.getText());
                        double deuAmount = invoiceAmount - (cashAmount + chequeAmount);
                        double deuAmount2 = Math.round(deuAmount * 100.0) / 100.0;

                        txtDeuAMount.setText(String.valueOf(deuAmount2));

                    } catch (Exception e) {
                        e.printStackTrace();
                    }
                    new DeliveryInvoice().addCheck(txtChequeNimber, txtBank, txtCheckAmount, dcReturnDate, tblCheck);
                }
            }
        }
    }//GEN-LAST:event_txtCheckAmountKeyTyped

    private void txtCusNameFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtCusNameFocusGained
        // TODO add your handling code here:

    }//GEN-LAST:event_txtCusNameFocusGained

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmDeliveryInvoice.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmDeliveryInvoice.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmDeliveryInvoice.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmDeliveryInvoice.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frmDeliveryInvoice(tblDI, txtRouteIdDI, tpDelivery).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAdd;
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnSave;
    private com.toedter.calendar.JDateChooser dcReturnDate;
    private com.toedter.calendar.JDateChooser dcSaleDate;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel11;
    private javax.swing.JPanel jPanel12;
    private javax.swing.JPanel jPanel13;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable tblCheck;
    private javax.swing.JTextField txtBalance;
    private javax.swing.JTextField txtBank;
    private javax.swing.JTextField txtCashPay;
    private javax.swing.JTextField txtCheckAmount;
    private javax.swing.JTextField txtChequeNimber;
    private javax.swing.JTextField txtChequePay;
    private javax.swing.JTextField txtCurrentCrdit;
    private javax.swing.JTextField txtCusId;
    private javax.swing.JTextField txtCusName;
    private javax.swing.JTextField txtDeuAMount;
    private javax.swing.JTextField txtInvoiceAmount;
    // End of variables declaration//GEN-END:variables
}
