/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package v;

import c.CashChequeBookListner;
import c.Errormzg;
import c.StockControler;
import c.SupplierTableView;
import c.grncashcontroller;
import java.awt.Color;
import java.awt.event.KeyEvent;
import java.util.Date;
import java.util.Vector;
import javax.swing.JButton;
import javax.swing.JOptionPane;
import javax.swing.JTextField;
import javax.swing.table.DefaultTableModel;
import pojo.Product;
import pojo.Supplier;

/**
 *
 * @author User
 */
public class grncash extends javax.swing.JFrame {

    Supplier supplier;
    double crntvalue;
    Date grndate;
    pojo.Grn grnid;
    pojo.GrnLog grnlgid;
    pojo.Supplier findSupIdByName;
    Product findPridByName;
    double txtbuyingprice;
    double txtquantity;
    double total;
    StockControler st;

    /**
     * Creates new form grncash
     */
    public grncash() {
        initComponents();
        c.CashChequeBookListner.getInstance().loadBankToCombo(cmbbank);

    }

    public void setvalues(Supplier sup, double crntvalue, Date grndate) {
        this.supplier = sup;
        this.crntvalue = crntvalue;
        this.grndate = grndate;
        lblsupid.setText(sup.getId().toString());
        lblsupcredit.setText(sup.getCurrentCredit().toString());
        lbltotal.setText(String.valueOf(crntvalue));
        lbldate.setText(grndate.toString());
    }

    public void setgrnvaluse(pojo.Supplier supid) {
        this.findSupIdByName = supid;
    }

    public void setgrnlogvaluse(Product prid, double buyingprice, double quantity, double tot) {
        this.findPridByName = prid;
        this.txtbuyingprice = buyingprice;
        this.txtquantity = quantity;
        this.total = tot;
    }
int grnsaveid;
    public int saveGrnNloadGrnCash() {
        try {
            st = new StockControler();

            //        System.out.println(findSupIdByName.getAdressLine2());
          grnsaveid = st.grnsave(findSupIdByName, grndate);

            if (grnsaveid != 0) {
                pojo.Grn grnid = new m.Grn().getBy(grnsaveid);
                int grnlogsave = st.grnlogsave(grnid, findPridByName, txtbuyingprice, txtquantity, total);
                if (grnlogsave != 0) {
                    Errormzg.displayconfirmMessage("Stock added");
                    int i = st.getaverageprice(findPridByName);
                    if (i != 0) {
                        pojo.GrnLog grnlgid = new m.GrnLog().getById(grnlogsave);
                        this.grnid = grnid;
                        this.grnlgid = grnlgid;
                        return i;
                    } else {
                        Errormzg.displayerrorMessage("unable to Update Products");
                        return 0;
                    }
                } else {
                    Errormzg.displayerrorMessage("unable to add stock");
                    return 0;
                }
            } else {

                Errormzg.displayerrorMessage("Unable to save Grn");
                return 0;

            }
        } catch (Exception e) {
            e.printStackTrace();
            return 0;

        }

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jPanel9 = new javax.swing.JPanel();
        jLabel12 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        txtchequeno = new javax.swing.JTextField();
        cmbbank = new javax.swing.JComboBox<>();
        jLabel23 = new javax.swing.JLabel();
        radiocheque = new javax.swing.JRadioButton();
        radiocash = new javax.swing.JRadioButton();
        lbltotal = new javax.swing.JLabel();
        txtchequeamount = new javax.swing.JTextField();
        jLabel25 = new javax.swing.JLabel();
        lblsupcredit = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        txttototalamount = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblchequedetails = new javax.swing.JTable();
        jLabel27 = new javax.swing.JLabel();
        btnpay = new javax.swing.JButton();
        btnreset = new javax.swing.JButton();
        lblsupid = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        lbldate = new javax.swing.JLabel();
        jLabel28 = new javax.swing.JLabel();
        chkdate = new com.toedter.calendar.JDateChooser();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setType(java.awt.Window.Type.POPUP);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        jPanel9.setBackground(new java.awt.Color(255, 255, 255));
        jPanel9.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Payment Details", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Times New Roman", 1, 14), new java.awt.Color(255, 0, 51))); // NOI18N
        jPanel9.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel12.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 0, 51));
        jLabel12.setText("Supllier Credit :");
        jPanel9.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(547, 71, 110, 35));

        jLabel21.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel21.setText("Payment Type");
        jPanel9.add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(16, 71, 112, 39));

        jLabel22.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel22.setText("Cheque Number");
        jPanel9.add(jLabel22, new org.netbeans.lib.awtextra.AbsoluteConstraints(16, 164, -1, 33));

        txtchequeno.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        txtchequeno.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(102, 255, 0)));
        txtchequeno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtchequenoActionPerformed(evt);
            }
        });
        jPanel9.add(txtchequeno, new org.netbeans.lib.awtextra.AbsoluteConstraints(134, 163, 197, 34));

        cmbbank.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        cmbbank.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(102, 255, 0)));
        jPanel9.add(cmbbank, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 220, 88, 34));

        jLabel23.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel23.setText("Bank");
        jPanel9.add(jLabel23, new org.netbeans.lib.awtextra.AbsoluteConstraints(16, 221, 101, 33));

        buttonGroup1.add(radiocheque);
        radiocheque.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        radiocheque.setText("Cheque");
        radiocheque.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(102, 255, 0)));
        radiocheque.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radiochequeActionPerformed(evt);
            }
        });
        jPanel9.add(radiocheque, new org.netbeans.lib.awtextra.AbsoluteConstraints(138, 77, 76, 33));

        buttonGroup1.add(radiocash);
        radiocash.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        radiocash.setText("Cash");
        radiocash.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(102, 255, 0)));
        radiocash.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                radiocashItemStateChanged(evt);
            }
        });
        radiocash.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                radiocashStateChanged(evt);
            }
        });
        radiocash.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radiocashActionPerformed(evt);
            }
        });
        jPanel9.add(radiocash, new org.netbeans.lib.awtextra.AbsoluteConstraints(232, 77, 82, 33));

        lbltotal.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        lbltotal.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(102, 255, 0)));
        jPanel9.add(lbltotal, new org.netbeans.lib.awtextra.AbsoluteConstraints(134, 121, 197, 35));

        txtchequeamount.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        txtchequeamount.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(102, 255, 0)));
        txtchequeamount.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtchequeamountActionPerformed(evt);
            }
        });
        txtchequeamount.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtchequeamountKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtchequeamountKeyTyped(evt);
            }
        });
        jPanel9.add(txtchequeamount, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 320, 200, 36));

        jLabel25.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel25.setText("Cheque Amount");
        jPanel9.add(jLabel25, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 320, -1, 35));

        lblsupcredit.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblsupcredit.setForeground(new java.awt.Color(255, 0, 0));
        jPanel9.add(lblsupcredit, new org.netbeans.lib.awtextra.AbsoluteConstraints(675, 71, 95, 35));

        jLabel26.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel26.setText("Current Total");
        jPanel9.add(jLabel26, new org.netbeans.lib.awtextra.AbsoluteConstraints(16, 121, 100, 38));

        txttototalamount.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        txttototalamount.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(102, 255, 0)));
        txttototalamount.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txttototalamountActionPerformed(evt);
            }
        });
        txttototalamount.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txttototalamountKeyTyped(evt);
            }
        });
        jPanel9.add(txttototalamount, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 380, 200, 39));

        tblchequedetails.setRowHeight(25);
        tblchequedetails.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        tblchequedetails.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Cheque Number", "Bank", "Amont", "Cheque Date"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblchequedetails.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblchequedetailsMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblchequedetails);
        if (tblchequedetails.getColumnModel().getColumnCount() > 0) {
            tblchequedetails.getColumnModel().getColumn(0).setResizable(false);
            tblchequedetails.getColumnModel().getColumn(1).setResizable(false);
            tblchequedetails.getColumnModel().getColumn(2).setResizable(false);
            tblchequedetails.getColumnModel().getColumn(3).setResizable(false);
        }

        jPanel9.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(349, 163, 421, 145));

        jLabel27.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel27.setText("Total Date");
        jPanel9.add(jLabel27, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 270, -1, 39));

        btnpay.setBackground(new java.awt.Color(255, 255, 255));
        btnpay.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        btnpay.setText("Pay");
        btnpay.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btnpayMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                btnpayMouseReleased(evt);
            }
        });
        jPanel9.add(btnpay, new org.netbeans.lib.awtextra.AbsoluteConstraints(456, 357, 104, 49));

        btnreset.setBackground(new java.awt.Color(255, 255, 255));
        btnreset.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        btnreset.setText("Reset");
        btnreset.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnresetMouseClicked(evt);
            }
        });
        btnreset.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                btnresetKeyTyped(evt);
            }
        });
        jPanel9.add(btnreset, new org.netbeans.lib.awtextra.AbsoluteConstraints(616, 356, 105, 51));

        lblsupid.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jPanel9.add(lblsupid, new org.netbeans.lib.awtextra.AbsoluteConstraints(675, 30, 95, 35));

        jLabel13.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(255, 0, 51));
        jLabel13.setText("Supllier Id:");
        jPanel9.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(547, 30, 110, 35));
        jPanel9.add(lbldate, new org.netbeans.lib.awtextra.AbsoluteConstraints(16, 30, 118, 35));

        jLabel28.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel28.setText("Total Amount");
        jPanel9.add(jLabel28, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 370, -1, 39));

        chkdate.setDateFormatString("yyyy-MM-dd");
        chkdate.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jPanel9.add(chkdate, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 260, 190, 40));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel9, javax.swing.GroupLayout.DEFAULT_SIZE, 789, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel9, javax.swing.GroupLayout.DEFAULT_SIZE, 448, Short.MAX_VALUE)
                .addContainerGap())
        );

        jPanel9.getAccessibleContext().setAccessibleName("Payment Detail");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void txtchequenoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtchequenoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtchequenoActionPerformed

    private void txtchequeamountActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtchequeamountActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtchequeamountActionPerformed

    private void txttototalamountActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txttototalamountActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txttototalamountActionPerformed

    private void radiochequeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radiochequeActionPerformed
        // TODO add your handling code here:
        txtchequeno.setEnabled(true);
        cmbbank.setEnabled(true);
        txtchequeamount.setEnabled(true);
        tblchequedetails.setEnabled(true);
        txttototalamount.setDisabledTextColor(Color.red);
    }//GEN-LAST:event_radiochequeActionPerformed

    private void radiocashStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_radiocashStateChanged
        // TODO add your handling code here:

    }//GEN-LAST:event_radiocashStateChanged

    private void radiocashItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_radiocashItemStateChanged
        // TODO add your handling code here:
        if (radiocash.isSelected()) {

        } else if (radiocheque.isSelected()) {

        } else {
            Errormzg.displayerrorMessage("please select cash type");
        }
    }//GEN-LAST:event_radiocashItemStateChanged

    private void radiocashActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radiocashActionPerformed
        // TODO add your handling code here:
        txtchequeno.setEnabled(false);
        cmbbank.setEnabled(false);
        txtchequeamount.setEnabled(false);
        tblchequedetails.setEnabled(false);

    }//GEN-LAST:event_radiocashActionPerformed

    private void txtchequeamountKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtchequeamountKeyPressed
        // TODO add your handling code here:
        try {
            double totamount = 0.0;

            DefaultTableModel defaultTableModel = (DefaultTableModel) tblchequedetails.getModel();
            if (evt.getKeyChar() == KeyEvent.VK_ENTER) {
                Vector v = new Vector();
                if (!txtchequeno.getText().trim().isEmpty()) {
                    if (!cmbbank.getSelectedItem().toString().isEmpty()) {
                        if (!txtchequeamount.getText().isEmpty()) {
                            v.add(txtchequeno.getText().toString());
                            v.add(cmbbank.getSelectedItem().toString());
                            double chequeammount = Double.parseDouble(txtchequeamount.getText());
                            chequeammount = (Math.round(chequeammount * 100.0) / 100.0);
                            v.add(chequeammount);
                            v.add(((JTextField) chkdate.getDateEditor().getUiComponent()).getText());
                            defaultTableModel.addRow(v);
                            try {
                                totamount = Double.parseDouble(txttototalamount.getText());
                            } catch (Exception e) {
                                totamount = 0.0;
                            }
//                System.out.println(totamount);
                            double fullamount = totamount + chequeammount;
                            txttototalamount.setText(String.valueOf(fullamount));
                            txtchequeno.setText("");
                            txtchequeamount.setText("");
                            cmbbank.setSelectedItem(null);
                            txtchequeno.requestFocus();
                        } else {
                            Errormzg.displayerrorMessage("Empty Filds");
                        }
                    } else {
                        Errormzg.displayerrorMessage("Empty Filds");
                    }
                } else {
                    Errormzg.displayerrorMessage("Empty Filds");
                }

            }

        } catch (Exception e) {
            e.printStackTrace();
        }

    }//GEN-LAST:event_txtchequeamountKeyPressed
    public int pay() {
        try {
            double totammount = Double.parseDouble(txttototalamount.getText());
            if (radiocash.isSelected() == true || radiocheque.isShowing() == true) {
                int saved = 0;
                if (!txttototalamount.getText().isEmpty()) {
                    if (radiocash.isSelected() == true) {
                        saved = new grncashcontroller().saveMoneyBook(1, totammount, grndate, crntvalue, supplier);
                    } else {
                        if (tblchequedetails.getRowCount() != 0) {
                            saved = new grncashcontroller().saveMoneyBook(2, totammount, grndate, crntvalue, supplier, tblchequedetails);
                        } else {
                            Errormzg.displayerrorMessage("Please add cheques to table");
                        }

                    }
                    if (saved != 0) {
                        Errormzg.displayconfirmMessage("Payment Recorded");
                        new report.Psmodle().grn(grnsaveid);
                        this.dispose();
                    } else {
                        Errormzg.displayerrorMessage("somthing went wrong");
                    }
                } else {
                    Errormzg.displayerrorMessage("please set total");
                }
            } else {
                Errormzg.displayerrorMessage("please select cash type");
            }
            return 1;

        } catch (Exception e) {
            e.printStackTrace();
            return 0;
        }

    }

    private void btnpayMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnpayMouseReleased
        // TODO add your handling code here:

        if (radiocheque.isSelected() || radiocash.isSelected()) {
            if (!txttototalamount.getText().trim().isEmpty()) {
                double totammount = Double.parseDouble(txttototalamount.getText());
                double tot1 = Double.parseDouble(lblsupcredit.getText());
                double tot2 = Double.parseDouble(lbltotal.getText());
                if (tot1 >= 0) {
                    if (tot2 >= 0) {
                        if (totammount >= 0) {
                            if (tot1 + tot2 >= totammount) {
                                int done = saveGrnNloadGrnCash();
                                if (done != 0) {
                                    pay();
                                } else {
                                    Errormzg.displayerrorMessage("Unable to save stock");
                                }

                            } else {
                                Errormzg.displayerrorMessage("please enter less value");
                            }
                        }
                    }
                }
            } else {
                Errormzg.displayerrorMessage("Empty Fields");
            }
        } else {
            Errormzg.displayerrorMessage("please select pay method");
        }


    }//GEN-LAST:event_btnpayMouseReleased

    private void tblchequedetailsMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblchequedetailsMouseClicked
        // TODO add your handling code here:
        DefaultTableModel defaultTableModel = (DefaultTableModel) tblchequedetails.getModel();
        int selectedRow = tblchequedetails.getSelectedRow();
        double tot = Double.parseDouble(tblchequedetails.getValueAt(selectedRow, 2).toString());
        System.out.println(tot);
        txttototalamount.setText(String.valueOf(Double.parseDouble(txttototalamount.getText()) - tot));
        if (selectedRow != -1) {
            defaultTableModel.removeRow(selectedRow);
        }


    }//GEN-LAST:event_tblchequedetailsMouseClicked

    private void txtchequeamountKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtchequeamountKeyTyped
        // TODO add your handling code here:
        char vChar = evt.getKeyChar();
        if (!(Character.isDigit(vChar)
                || (vChar == KeyEvent.VK_BACK_SPACE)
                || (vChar == KeyEvent.VK_DELETE) || vChar == KeyEvent.VK_PERIOD)) {
            evt.consume();
        }
    }//GEN-LAST:event_txtchequeamountKeyTyped

    private void txttototalamountKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txttototalamountKeyTyped
        // TODO add your handling code here:
        char vChar = evt.getKeyChar();
        if (!(Character.isDigit(vChar)
                || (vChar == KeyEvent.VK_BACK_SPACE)
                || (vChar == KeyEvent.VK_DELETE) || vChar == KeyEvent.VK_PERIOD)) {
            evt.consume();
        }
    }//GEN-LAST:event_txttototalamountKeyTyped

    private void btnpayMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnpayMousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnpayMousePressed
    public void clearcash() {
        lbltotal.setText("");
        txtchequeno.setText("");
        cmbbank.setSelectedItem(null);
        txtchequeamount.setText("");
        txttototalamount.setText("");
        lblsupid.setText("");
        lblsupcredit.setText("");
        DefaultTableModel model = (DefaultTableModel) this.tblchequedetails.getModel();
        model.setRowCount(0);

    }
    private void btnresetKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_btnresetKeyTyped
        // TODO add your handling code here:

    }//GEN-LAST:event_btnresetKeyTyped

    private void btnresetMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnresetMouseClicked
        // TODO add your handling code here:
        clearcash();
    }//GEN-LAST:event_btnresetMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(grncash.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(grncash.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(grncash.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(grncash.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new grncash().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnpay;
    private javax.swing.JButton btnreset;
    private javax.swing.ButtonGroup buttonGroup1;
    private com.toedter.calendar.JDateChooser chkdate;
    private javax.swing.JComboBox<String> cmbbank;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lbldate;
    private javax.swing.JLabel lblsupcredit;
    private javax.swing.JLabel lblsupid;
    private javax.swing.JLabel lbltotal;
    private javax.swing.JRadioButton radiocash;
    private javax.swing.JRadioButton radiocheque;
    private javax.swing.JTable tblchequedetails;
    private javax.swing.JTextField txtchequeamount;
    private javax.swing.JTextField txtchequeno;
    private javax.swing.JTextField txttototalamount;
    // End of variables declaration//GEN-END:variables
}
