/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package v;

import java.awt.Color;
import java.awt.Font;

/**
 *
 * @author suhada
 */
public class Status extends javax.swing.JPanel {

    /**
     * Creates new form Status
     */
    public Status() {
        initComponents();
        addAncestorListener(c.StatusListner.getInstance());
        c.StatusListner.getInstance().setStatus(this);
    }
    public static Status Status = null;

    public static Status getInstance() {
        if (Status == null) {
            Status = new Status();
        }
        return Status;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane2 = new javax.swing.JScrollPane();
        jPanel1 = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbl_currentstock = new javax.swing.JTable();
        jPanel11 = new javax.swing.JPanel();
        jPanel12 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        lbl_cash_total = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        lbl_bank_total = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        lbl_total_cash = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        lbl_supplier_credit = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        lbl_customer_credit = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        lbl_route_credit = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        lbl_total_credit_receive = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        lbl_balance = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        lbl_income_today = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        lbl_expend_today = new javax.swing.JLabel();
        jPanel6 = new javax.swing.JPanel();
        jPanel7 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        lbl_customer_count = new javax.swing.JLabel();
        jPanel8 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        lbl_customer_total_credit = new javax.swing.JLabel();
        jPanel9 = new javax.swing.JPanel();
        jPanel10 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        lbl_employee_count = new javax.swing.JLabel();

        setBackground(c.View.getInstance().colorTheme);
        setPreferredSize(new java.awt.Dimension(600, 500));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                jPanel1MouseMoved(evt);
            }
        });

        jPanel5.setBackground(new java.awt.Color(255, 255, 255));
        jPanel5.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Current Stock", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 14), c.View.getInstance().colorTheme)); // NOI18N

        jScrollPane1.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));

        tbl_currentstock.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        tbl_currentstock.setShowVerticalLines(false);
        tbl_currentstock.setRowHeight(25);
        tbl_currentstock.setGridColor(c.View.getInstance().colorTheme);
        tbl_currentstock.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        tbl_currentstock.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Product Name", "Current Stock", "Current Price"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tbl_currentstock.getTableHeader().setFont(new Font(Font.SERIF, Font.BOLD, 16));
        tbl_currentstock.setRowHeight(30);
        jScrollPane1.getViewport().setBackground(Color.white);
        jScrollPane1.setViewportView(tbl_currentstock);
        if (tbl_currentstock.getColumnModel().getColumnCount() > 0) {
            tbl_currentstock.getColumnModel().getColumn(0).setResizable(false);
            tbl_currentstock.getColumnModel().getColumn(0).setPreferredWidth(40);
            tbl_currentstock.getColumnModel().getColumn(1).setResizable(false);
            tbl_currentstock.getColumnModel().getColumn(2).setResizable(false);
            tbl_currentstock.getColumnModel().getColumn(3).setResizable(false);
        }

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1)
                .addContainerGap())
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 190, Short.MAX_VALUE)
                .addContainerGap())
        );

        jPanel11.setBackground(new java.awt.Color(255, 255, 255));
        jPanel11.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT));

        jPanel12.setBackground(new java.awt.Color(255, 255, 255));
        jPanel12.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEmptyBorder(2, 2, 2, 2)));
        jPanel12.setPreferredSize(new java.awt.Dimension(400, 250));
        jPanel12.setLayout(new java.awt.GridLayout(8, 3, 5, 5));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel1.setText("Cash Total");
        jLabel1.setPreferredSize(new java.awt.Dimension(0, 25));
        jPanel12.add(jLabel1);

        jLabel13.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N
        jLabel13.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel13.setPreferredSize(new java.awt.Dimension(0, 25));
        jPanel12.add(jLabel13);

        lbl_cash_total.setBackground(new java.awt.Color(204, 255, 204));
        lbl_cash_total.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N
        lbl_cash_total.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl_cash_total.setOpaque(true);
        lbl_cash_total.setPreferredSize(new java.awt.Dimension(0, 25));
        jPanel12.add(lbl_cash_total);

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel9.setText("Bank Total");
        jLabel9.setPreferredSize(new java.awt.Dimension(0, 25));
        jPanel12.add(jLabel9);

        jLabel8.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N
        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel8.setPreferredSize(new java.awt.Dimension(0, 25));
        jPanel12.add(jLabel8);

        lbl_bank_total.setBackground(new java.awt.Color(204, 255, 204));
        lbl_bank_total.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N
        lbl_bank_total.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl_bank_total.setOpaque(true);
        lbl_bank_total.setPreferredSize(new java.awt.Dimension(0, 25));
        jPanel12.add(lbl_bank_total);

        jLabel12.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel12.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel12.setText("Money Total");
        jPanel12.add(jLabel12);
        jPanel12.add(jLabel22);

        lbl_total_cash.setBackground(new java.awt.Color(255, 255, 255));
        lbl_total_cash.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl_total_cash.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 0, 0, 0, new java.awt.Color(0, 0, 0)));
        lbl_total_cash.setOpaque(true);
        jPanel12.add(lbl_total_cash);

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel7.setText("Suppliers Credit");
        jLabel7.setPreferredSize(new java.awt.Dimension(0, 25));
        jPanel12.add(jLabel7);

        jLabel16.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N
        jLabel16.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel16.setPreferredSize(new java.awt.Dimension(0, 25));
        jPanel12.add(jLabel16);

        lbl_supplier_credit.setBackground(new java.awt.Color(255, 204, 204));
        lbl_supplier_credit.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N
        lbl_supplier_credit.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl_supplier_credit.setOpaque(true);
        lbl_supplier_credit.setPreferredSize(new java.awt.Dimension(0, 25));
        jPanel12.add(lbl_supplier_credit);

        jLabel18.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel18.setText("Customer Credit");
        jLabel18.setPreferredSize(new java.awt.Dimension(0, 25));
        jPanel12.add(jLabel18);

        lbl_customer_credit.setBackground(new java.awt.Color(255, 255, 255));
        lbl_customer_credit.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N
        lbl_customer_credit.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl_customer_credit.setOpaque(true);
        lbl_customer_credit.setPreferredSize(new java.awt.Dimension(0, 25));
        jPanel12.add(lbl_customer_credit);

        jLabel11.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N
        jLabel11.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel11.setPreferredSize(new java.awt.Dimension(0, 25));
        jPanel12.add(jLabel11);

        jLabel17.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel17.setText("Route Credit");
        jLabel17.setPreferredSize(new java.awt.Dimension(0, 25));
        jPanel12.add(jLabel17);

        lbl_route_credit.setBackground(new java.awt.Color(255, 255, 255));
        lbl_route_credit.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N
        lbl_route_credit.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl_route_credit.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(0, 0, 0)));
        lbl_route_credit.setOpaque(true);
        lbl_route_credit.setPreferredSize(new java.awt.Dimension(0, 25));
        jPanel12.add(lbl_route_credit);

        jLabel20.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N
        jLabel20.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel20.setPreferredSize(new java.awt.Dimension(0, 25));
        jPanel12.add(jLabel20);

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel10.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel10.setText("Total Credit Receive");
        jLabel10.setPreferredSize(new java.awt.Dimension(0, 25));
        jPanel12.add(jLabel10);

        jLabel14.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N
        jLabel14.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel14.setPreferredSize(new java.awt.Dimension(0, 25));
        jPanel12.add(jLabel14);

        lbl_total_credit_receive.setBackground(new java.awt.Color(255, 204, 204));
        lbl_total_credit_receive.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N
        lbl_total_credit_receive.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl_total_credit_receive.setOpaque(true);
        lbl_total_credit_receive.setPreferredSize(new java.awt.Dimension(0, 25));
        jPanel12.add(lbl_total_credit_receive);

        jLabel15.setPreferredSize(new java.awt.Dimension(0, 25));
        jPanel12.add(jLabel15);

        jLabel19.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N
        jLabel19.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel19.setPreferredSize(new java.awt.Dimension(0, 25));
        jPanel12.add(jLabel19);

        lbl_balance.setBackground(new java.awt.Color(204, 204, 255));
        lbl_balance.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N
        lbl_balance.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl_balance.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 0, 0, 0, new java.awt.Color(0, 0, 0)));
        lbl_balance.setOpaque(true);
        lbl_balance.setPreferredSize(new java.awt.Dimension(0, 25));
        jPanel12.add(lbl_balance);

        jPanel11.add(jPanel12);

        jPanel2.setBackground(new java.awt.Color(244, 244, 244));
        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Today Income/Expend Status", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 14), c.View.getInstance().colorTheme)); // NOI18N

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));
        jPanel3.setMaximumSize(new java.awt.Dimension(250, 2147483647));
        jPanel3.setMinimumSize(new java.awt.Dimension(250, 14));
        jPanel3.setPreferredSize(new java.awt.Dimension(250, 53));
        jPanel3.setLayout(new javax.swing.BoxLayout(jPanel3, javax.swing.BoxLayout.LINE_AXIS));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Today Income");
        jLabel2.setMaximumSize(new java.awt.Dimension(110, 14));
        jLabel2.setMinimumSize(new java.awt.Dimension(110, 14));
        jLabel2.setPreferredSize(new java.awt.Dimension(130, 14));
        jPanel3.add(jLabel2);

        lbl_income_today.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lbl_income_today.setText("00");
        lbl_income_today.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        lbl_income_today.setMaximumSize(new java.awt.Dimension(140, 14));
        lbl_income_today.setMinimumSize(new java.awt.Dimension(140, 14));
        lbl_income_today.setPreferredSize(new java.awt.Dimension(140, 14));
        jPanel3.add(lbl_income_today);

        jPanel4.setBackground(new java.awt.Color(255, 255, 255));
        jPanel4.setMaximumSize(new java.awt.Dimension(250, 2147483647));
        jPanel4.setMinimumSize(new java.awt.Dimension(250, 14));
        jPanel4.setPreferredSize(new java.awt.Dimension(250, 53));
        jPanel4.setLayout(new javax.swing.BoxLayout(jPanel4, javax.swing.BoxLayout.LINE_AXIS));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("Today Expend");
        jLabel3.setMaximumSize(new java.awt.Dimension(110, 14));
        jLabel3.setMinimumSize(new java.awt.Dimension(110, 14));
        jLabel3.setPreferredSize(new java.awt.Dimension(110, 14));
        jPanel4.add(jLabel3);

        lbl_expend_today.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lbl_expend_today.setText("00");
        lbl_expend_today.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        lbl_expend_today.setMaximumSize(new java.awt.Dimension(140, 14));
        lbl_expend_today.setMinimumSize(new java.awt.Dimension(140, 14));
        lbl_expend_today.setPreferredSize(new java.awt.Dimension(140, 14));
        jPanel4.add(lbl_expend_today);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(11, 11, 11)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(6, 6, 6)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(21, Short.MAX_VALUE))
        );

        jPanel11.add(jPanel2);

        jPanel6.setBackground(new java.awt.Color(244, 244, 244));
        jPanel6.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Customer Status", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 14), c.View.getInstance().colorTheme)); // NOI18N

        jPanel7.setBackground(new java.awt.Color(255, 255, 255));
        jPanel7.setMaximumSize(new java.awt.Dimension(250, 2147483647));
        jPanel7.setPreferredSize(new java.awt.Dimension(250, 53));
        jPanel7.setLayout(new javax.swing.BoxLayout(jPanel7, javax.swing.BoxLayout.LINE_AXIS));

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("Customer Count");
        jLabel4.setMaximumSize(new java.awt.Dimension(110, 14));
        jLabel4.setMinimumSize(new java.awt.Dimension(110, 14));
        jLabel4.setPreferredSize(new java.awt.Dimension(130, 14));
        jPanel7.add(jLabel4);

        lbl_customer_count.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lbl_customer_count.setText("00");
        lbl_customer_count.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        lbl_customer_count.setMaximumSize(new java.awt.Dimension(140, 14));
        lbl_customer_count.setMinimumSize(new java.awt.Dimension(140, 14));
        lbl_customer_count.setPreferredSize(new java.awt.Dimension(140, 14));
        jPanel7.add(lbl_customer_count);

        jPanel8.setBackground(new java.awt.Color(255, 255, 255));
        jPanel8.setMaximumSize(new java.awt.Dimension(250, 2147483647));
        jPanel8.setPreferredSize(new java.awt.Dimension(250, 53));
        jPanel8.setLayout(new javax.swing.BoxLayout(jPanel8, javax.swing.BoxLayout.LINE_AXIS));

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("Total credit");
        jLabel5.setMaximumSize(new java.awt.Dimension(110, 14));
        jLabel5.setMinimumSize(new java.awt.Dimension(110, 14));
        jLabel5.setPreferredSize(new java.awt.Dimension(130, 14));
        jPanel8.add(jLabel5);

        lbl_customer_total_credit.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lbl_customer_total_credit.setText("00");
        lbl_customer_total_credit.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        lbl_customer_total_credit.setMaximumSize(new java.awt.Dimension(140, 14));
        lbl_customer_total_credit.setMinimumSize(new java.awt.Dimension(140, 14));
        lbl_customer_total_credit.setPreferredSize(new java.awt.Dimension(140, 14));
        jPanel8.add(lbl_customer_total_credit);

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel8, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel11.add(jPanel6);

        jPanel9.setBackground(new java.awt.Color(244, 244, 244));
        jPanel9.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Employee Status", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 14), c.View.getInstance().colorTheme)); // NOI18N

        jPanel10.setBackground(new java.awt.Color(255, 255, 255));
        jPanel10.setMaximumSize(new java.awt.Dimension(250, 2147483647));
        jPanel10.setPreferredSize(new java.awt.Dimension(250, 53));
        jPanel10.setLayout(new javax.swing.BoxLayout(jPanel10, javax.swing.BoxLayout.LINE_AXIS));

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setText("Employee Count");
        jLabel6.setMaximumSize(new java.awt.Dimension(110, 14));
        jLabel6.setMinimumSize(new java.awt.Dimension(110, 14));
        jLabel6.setPreferredSize(new java.awt.Dimension(130, 14));
        jPanel10.add(jLabel6);

        lbl_employee_count.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lbl_employee_count.setText("00");
        lbl_employee_count.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        lbl_employee_count.setMaximumSize(new java.awt.Dimension(140, 14));
        lbl_employee_count.setMinimumSize(new java.awt.Dimension(140, 14));
        lbl_employee_count.setPreferredSize(new java.awt.Dimension(140, 14));
        jPanel10.add(lbl_employee_count);

        javax.swing.GroupLayout jPanel9Layout = new javax.swing.GroupLayout(jPanel9);
        jPanel9.setLayout(jPanel9Layout);
        jPanel9Layout.setHorizontalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel9Layout.setVerticalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel10, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(64, Short.MAX_VALUE))
        );

        jPanel11.add(jPanel9);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel11, javax.swing.GroupLayout.PREFERRED_SIZE, 1061, Short.MAX_VALUE)
                    .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel11, javax.swing.GroupLayout.DEFAULT_SIZE, 502, Short.MAX_VALUE)
                .addContainerGap())
        );

        jScrollPane2.setViewportView(jPanel1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 937, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 493, Short.MAX_VALUE)
                .addContainerGap())
        );

        getAccessibleContext().setAccessibleName("Status");
    }// </editor-fold>//GEN-END:initComponents

    private void jPanel1MouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel1MouseMoved
        // TODO add your handling code here:

    }//GEN-LAST:event_jPanel1MouseMoved


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    public javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel11;
    private javax.swing.JPanel jPanel12;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    public javax.swing.JLabel lbl_balance;
    public javax.swing.JLabel lbl_bank_total;
    public javax.swing.JLabel lbl_cash_total;
    public javax.swing.JLabel lbl_customer_count;
    public javax.swing.JLabel lbl_customer_credit;
    public javax.swing.JLabel lbl_customer_total_credit;
    public javax.swing.JLabel lbl_employee_count;
    public javax.swing.JLabel lbl_expend_today;
    public javax.swing.JLabel lbl_income_today;
    public javax.swing.JLabel lbl_route_credit;
    public javax.swing.JLabel lbl_supplier_credit;
    public javax.swing.JLabel lbl_total_cash;
    public javax.swing.JLabel lbl_total_credit_receive;
    public javax.swing.JTable tbl_currentstock;
    // End of variables declaration//GEN-END:variables
}
